name: Rclone GDrive
version: "0.1"
slug: rclone_gdrive
description: Testovací Rclone addon
arch: ["arm64", "amd64"]   # arm64 pro HA, amd64 pro PC test
startup: "before"
boot: "auto"
map:
  config: true
image: "rclone_gdrive_local"
