ARG BUILD_FROM=ghcr.io/home-assistant/aarch64-base:latest
FROM $BUILD_FROM

# Instalace Rclone
RUN apk add --no-cache rclone

# Nastavení pracovního adresáře
WORKDIR /config

# Start add-onu: výpis verze (později můžeš nahradit skriptem)
CMD ["rclone", "--version"]
