ARG BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest
FROM $BUILD_FROM

# Nainstalujeme Rclone
RUN apk add --no-cache rclone

# Nastavení pracovního adresáře
WORKDIR /config

# Spuštění add-onu
CMD ["rclone", "--version"]
